---
version: 2.1

executors:
  cli:
    docker:
      - image: circleci/circleci-cli:latest
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD


workflows:
  all:
    jobs:
      - validate:
        executor: cli
        steps:
          - checkout
          - run: circleci config pack src | circleci orb validate -
        filters:
          branches:
            only: orb_terraform
      - created-orb:
        executor: cli
        steps:
          - checkout
          - run: circleci orb create lovepop/terraform --private --token $CIRCLE_TOKEN
        requires:
            - validate
        filters:
          branches:
            only: orb_terraform
      - publish-dev:
        executor: cli
        steps:
          - checkout
          - run: circleci config pack src | circleci orb publish - lovepop/terraform@dev:$CIRCLE_SHA1 --token $CIRCLE_TOKEN
        requires:
            - created-orb
        filters:
          branches:
            only: orb_terraform
      - promote-prod:
        executor: cli
        steps:
          - checkout
          - run: circleci orb publish promote lovepop/terraform@dev:$CIRCLE_SHA1 patch --token $CIRCLE_TOKEN
        requires:
            - publish-dev
        filters:
          branches:
            only: orb_terraform
