description: "Build and push the docker image"

executor:
  name: default
  image: devops
  tag: main.latest

parameters:
  image_repo:
    description: "The repository in ECR to push images too."
    type: string
steps:
  - setup_remote_docker
  - checkout
  - docker_login
  - docker_build
  - docker-push:
      image_repo: <<parameters.image-repo>>
