description: >
  This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here.
  If you do not require an executor, you can simply delete this directory.
parameters:
  image:
    description: "The lovepop base image to use."
    type: string
  tag:
    description: "The image tag to use."
    type: string
docker:
  - image: docker.pkg.github.com/lovepopcards/base_images/<<parameters.image>>:<<parameters.tag>>
    auth:
      username: lovepopcards
      password: $GITHUB_TOKEN
